export const colors = {
    primary: '#0F172A',
    primaryDark: '#020617',
    primarySoft: '#F1F5F9',
    secondary: '#3B82F6',
    secondaryDark: '#2563EB',
    secondarySoft: '#DBEAFE',
    accent: '#8B5CF6',
    accentSoft: '#EDE9FE',
    danger: '#EF4444',
    dangerDark: '#B91C1C',
    dangerSoft: '#FEE2E2',
    warning: '#F59E0B',
    warningDark: '#B45309',
    warningSoft: '#FEF3C7',
    info: '#0EA5E9',
    infoSoft: '#E0F2FE',
    background: '#F8FAFC',
    backgroundAccent: '#F1F5F9',
    surface: '#FFFFFF',
    surfaceMuted: '#F8FAFC',
    surfaceDark: '#111C30',
    surfaceDarkMuted: '#18253A',
    text: '#0F172A',
    textSecondary: '#64748B',
    textMuted: '#94A3B8',
    textOnDark: '#F8FAFC',
    textOnDarkMuted: '#CBD5E1',
    border: '#E2E8F0',
    borderStrong: '#CBD5E1',
    borderSubtle: '#EEF2F7',
    success: '#10B981',
    successDark: '#047857',
    successSoft: '#D1FAE5',
    disabled: '#CBD5E1',
    overlay: 'rgba(2, 6, 23, 0.72)',
};

export const spacing = {
    xxs: 2,
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
    xxl: 40,
    xxxl: 48,
};

export const radii = {
    xs: 8,
    sm: 12,
    md: 16,
    lg: 24,
    xl: 32,
    pill: 999,
};

export const typography = {
    display: {
        fontSize: 38,
        lineHeight: 44,
        fontWeight: '800',
        color: colors.text,
        letterSpacing: -1,
    },
    hero: {
        fontSize: 32,
        lineHeight: 38,
        fontWeight: '800',
        color: colors.text,
        letterSpacing: -0.8,
    },
    h1: {
        fontSize: 28,
        lineHeight: 34,
        fontWeight: '800',
        color: colors.text,
        letterSpacing: -0.6,
    },
    h2: {
        fontSize: 22,
        lineHeight: 28,
        fontWeight: '700',
        color: colors.text,
        letterSpacing: -0.4,
    },
    h3: {
        fontSize: 18,
        lineHeight: 24,
        fontWeight: '700',
        color: colors.text,
        letterSpacing: -0.2,
    },
    body: {
        fontSize: 15,
        lineHeight: 22,
        color: colors.text,
    },
    bodySmall: {
        fontSize: 14,
        lineHeight: 20,
        color: colors.textSecondary,
    },
    caption: {
        fontSize: 12,
        lineHeight: 16,
        color: colors.textMuted,
        fontWeight: '600',
        letterSpacing: 0.5,
    },
    overline: {
        fontSize: 11,
        lineHeight: 14,
        color: colors.textMuted,
        fontWeight: '800',
        letterSpacing: 1.2,
        textTransform: 'uppercase',
    },
};

export const shadows = {
    small: {
        shadowColor: '#0F172A',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.06,
        shadowRadius: 6,
        elevation: 1,
    },
    medium: {
        shadowColor: '#0F172A',
        shadowOffset: { width: 0, height: 6 },
        shadowOpacity: 0.08,
        shadowRadius: 14,
        elevation: 4,
    },
    large: {
        shadowColor: '#0F172A',
        shadowOffset: { width: 0, height: 12 },
        shadowOpacity: 0.14,
        shadowRadius: 28,
        elevation: 10,
    },
};
